### ISSUE TITLE
bug: using vim.diagnostic.setqflist does not correctly format

### ISSUE THREAD

**Issue by hosaka** [stevearc/quicker.nvim#19]
### Neovim version (nvim -v)

v0.11.0-dev-381+gfb6c059dc

### Operating system/version

Ubuntu 22.04 LTS

### Describe the bug

Using `vim.diagnostic.setqflist` to populate the quicklist with LSP diagnostics will not show the source line, and only the diagnostic message. If I `expand()` and then `collapse()` it looks as expected.

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. `:lua vim.diagnostic.setqflist()`
![image](https://github.com/user-attachments/assets/f4d856d2-55a6-435b-b7d5-b4655e2b9b9e)
2. `:lua require("quicker").expand()` then `:lua require("quicker").collapse()`
![image](https://github.com/user-attachments/assets/d77b33a4-0903-433a-973c-226d1b93eb59)

### Expected Behavior

Quicklist contains the source line and the error right after calling the `vim.diagnostic.setqflist()`

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/quicker.nvim",
    config = function()
      require("quicker").setup({
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by hosaka** [comment]
Seems related to https://github.com/stevearc/quicker.nvim/issues/16 but I don't think it's the exact same issue.

**Comment by stevearc** [comment]
This is interesting. So...the way quickfix normally works is what you are currently seeing. `vim.diagnostic.setqflist()` will send the diagnostics to the quickfix and each item will have a bufnr, line number, and some "text". The "text" will be the text of the error, so with a stock Neovim you would expect the quicklist to show the lines that look like
```
src/leadermaps.lua|172|Undefined field `fs_stat`.
```

I have added some custom logic to `expand` to replace that text with the referenced line of source code and use the text instead as a virtual text message. We can assume this is a desirable change because we know people calling `expand` want to view more lines of the source buffers.

That is not always necessarily the desired behavior for _all_ uses of the quickfix, so I wouldn't feel comfortable performing that modification all the time. What do you think about if I made that part of the behavior of [quicker.refresh()](https://github.com/stevearc/quicker.nvim/?tab=readme-ov-file#refreshloclist_win)? For your use case, you would just call that after `vim.diagnostic.setqflist()`.

**Comment by hosaka** [comment]
I'm guessing that for a large list of buffers, reading/replacing the text with a source line will have a noticable delay and this shouldn't be the default behaviour untill `expand` is used explicitly. Calling `refresh()` after setting the quickfix makes total sense and would work nicely for me with the lsp diagnostics!
