### ISSUE TITLE
feature request: add options to set `max_height` and `min_height` globally

### ISSUE THREAD

**Issue by uwla** [stevearc/quicker.nvim#20]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Currently it is only possible to set `max_height` and `min_height` when calling `require('quicker').open({max_height=5})` but not if it is opened with `copen` or something else.

### Provide background

Set `max_height` globally, so it works even if the quick fix is not opened by this plugin API.

### What is the significance of this feature?

nice to have

**Comment by nullromo** [comment]
I have been using [Telescope.nvim](https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#default-mappings), and you can see in that mapping table they have a `<C-q>` mapping to send the results to the quickfix list. This is how I usually populate my quickfix list.

I wanted to change the max_height to 20 instead of 10. I tried using qf_helper, but even with `max_height = 20` in the qf_helper settings, opening the quickfix list from Telescope sets the height at 10 instead of 20.

**Comment by nullromo** [comment]
Nope, never figured it out yet.
