### ISSUE TITLE
feature request: Exclude filename from editor changes

### ISSUE THREAD

**Issue by mike-ap** [stevearc/quicker.nvim#28]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

First, thanks for another great plugin!

When a list includes both filename and test matches for a substitution command, both values are modified. Modifying a filename produces an error "does not support adding or reordering quickfix items".

list:
`app/controllers/foo_bar.rb                  ┃   54┃@foo_bar = "baz"`

substituter:
`%s/foo_bar/foo_baz`

### Provide background

I am trying to substitute matching terms, excluding filename matches. I can do this by modifying my search (e.g. "foo_bar$"), but I wonder if ignoring filenames in the *editor* makes sense as a default behavior.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
I wish I could, but we need the filenames. When you save changes in the quickfix, I parse the buffer and for each line I try to match it to one of the quickfix entries. This is done by trying to match the filename + lnum.
https://github.com/stevearc/quicker.nvim/blob/183041a46d6c908eefb1c23ea02cce9c8f41256e/lua/quicker/editor.lua#L157-L167

The only thing I could think of that might work would be to change how the buffer is rendered and make the filename + lnum virtual text instead of real text. Would require rewriting a good bit of this plugin though, and I'm not 100% sure it would work perfectly with the editor.

**Comment by stevearc** [comment]
@mike-ap I did the refactor I was talking about in #32. It actually worked better than I expected! I'm going to daily drive this for a while and then merge it in once I think it's stable enough. If you get a chance please try it out and let me know if you encounter any bugs or usability issues.
